### ISSUE TITLE
Remove public properties

### ISSUE THREAD

**Issue by greg0ire** [doctrine/sql-formatter#16]

**Comment by goetas** [comment]
I suggest to mark as private also `removeComments()` and `splitQuery()` currently public

**Comment by goetas** [comment]
> I suggest to mark as private also removeComments() and splitQuery() currently public

looking better, they are not used at all, so I guess can be just removed

**Comment by greg0ire** [comment]
> looking better, they are not used at all, so I guess can be just removed

wait :thinking: both are mentioned in the README, why did you want to mark them as private? I think they are deliberately part of the public API

**Comment by goetas** [comment]
> I think they are deliberately part of the public API

yes, but IMO they have nothing to do with this LIB

**Comment by greg0ire** [comment]
Good point at least about `splitQuery`!

https://github.com/doctrine/sql-formatter/blob/4db282d8904774d422794c2fa361be0206d704b4/README.md#L138

I think you're right, let's remove those.
