### ISSUE TITLE
Setup Github pages

### ISSUE THREAD

**Issue by greg0ire** [doctrine/sql-formatter#18]
http://jdorn.github.io seems to use `examples/examples.php`, it would be nice to have the same here and use the url next to the repo description.

**Comment by greg0ire** [comment]
In fact, it's using an `index.html` file that is on a branch called `gh-pages`. I think the README is enough, and if not, then we will use a `docs` directory like other Doctrine repositories. WDYT @goetas ?

**Comment by goetas** [comment]
is it worth the effort setting up gh-pages? why not go directly to docs directory like other Doctrine repositories ?

**Comment by greg0ire** [comment]
Ok let's just drop the branch then.
