### ISSUE TITLE
Prefer mbstring functions

### ISSUE THREAD

**Issue by greg0ire** [doctrine/sql-formatter#35]
See https://github.com/jdorn/sql-formatter/issues/85

Not sure why our coding standard does not enforce that, maybe it's too risky?

**Comment by goetas** [comment]
Not sure if is a good idea. When matching non utf8 characters, ordinary functions should be enough. Is there a case where mb is required?

**Comment by greg0ire** [comment]
It's indeed consistently slower (according to `tests/performance.php`), and I tried to build a failing test case from http://baldi.me/blog/emoji-in-sql … no dice. Let's just close this one.
