### ISSUE TITLE
Linebreak CASE… WHEN

### ISSUE THREAD

**Issue by greg0ire** [doctrine/sql-formatter#36]
See https://github.com/jdorn/sql-formatter/issues/83

**Comment by mvorisek** [comment]
Any idea how to implement this?

**Comment by mvorisek** [comment]
`then` and `else` should act as `(` and `end` as `)`

this would format SQL then like:
```
case when ... then
    xxx
when ... then
    yyy
end
```

**Comment by mvorisek** [comment]
@greg0ire can be closed
