### ISSUE TITLE
Missing tags?

### ISSUE THREAD

**Issue by reedy** [doctrine/sql-formatter#57]
https://packagist.org/packages/doctrine/sql-formatter shows 1.1.0 and 1.1.1 but I don't see any sign of them on https://github.com/doctrine/sql-formatter/tags or https://github.com/doctrine/sql-formatter/releases

Similarly https://github.com/doctrine/sql-formatter/tree/1.1.0 and https://github.com/doctrine/sql-formatter/tree/1.1.1 give a 404

**Comment by reedy** [comment]
But the commit it is showing for 1.1.1 is 1ad4f97f10cd0eef7ca7d3f5b7b1cf7e5806786f and that works...

Is there some magic going on?

**Comment by ostrolucky** [comment]
Those tags were incorrect and have been deleted, packagist just didn't pick up this change. They will be removed from packagist soon.

**Comment by ostrolucky** [comment]
Removed from packagist. Sorry if we caused any complications.

**Comment by reedy** [comment]
Thanks. No complications, just confusion :)
