### ISSUE TITLE
[Question] PostgreSQL Cast Operator

### ISSUE THREAD

**Issue by rodnaph** [doctrine/sql-formatter#66]
I noticed the PostgreSQL cast shortcut is incorrectly split, for example `123::bigint` becomes `123: :bigint`.

I can look at making a PR to support this, but first I wanted to check if there was interest in this tool supporting *platform specific* syntax... ?

**Comment by stof** [comment]
IIRC, the package already supports the `@variable` syntax of SQL Server, so I would say this  might be fine.

**Comment by slualexvas** [comment]
> I noticed the PostgreSQL cast shortcut is incorrectly split, for example `123::bigint` becomes `123: :bigint`.
> 
> I can look at making a PR to support this, but first I wanted to check if there was interest in this tool supporting _platform specific_ syntax... ?

Yes, it will be helpful for me

**Comment by bendavies** [comment]
this is fixed and can be closed
