### ISSUE TITLE
Adding many options as an or'ed list of flags

### ISSUE THREAD

**Issue by GingkoFr** [doctrine/sql-formatter#85]
Hello.

Why not adding an option to all suitable methods which would be an integer defaulting to zero, able to receive an or'ed list of flags, each ones defining an option (chosen among a list provided as **define('')**'s constants) ?
Many options could be defined there :

- Convert keywords to uppercases (or to lowercases)
- Convert function names to uppercases (or to lowercases)
- Add back-ticks wherever suitable
- Add 'AS' keyword before aliases if not already there
- Add line numbering to syntax highlighting
- Etc, etc

This would be largely open to future as an integer could potentially contain up to 32 options.

**Comment by greg0ire** [comment]
With a named constructor and php's named arguments feature, you'd be able to specify one flag while still relying on defaults for other flags. I don't think you can do that with a bitmask.

**Comment by GingkoFr** [comment]
Maybe php's named arguments could be an another way to do the same.
But this is a new feature not widely used yet.
Using bit flags for giving options is something already commonly used in PHP, like in the **[htmlspecialchars](https://www.php.net/manual/fr/function.htmlspecialchars)** function if I had to cite only one among many of them.

**Comment by greg0ire** [comment]
> Maybe php's named arguments could be an another way to do the same.

Not just the same, but better, as I pointed out.

>  But this is a new feature not widely used yet.

So what? named arguments are relatively new, don't you think that might explain why they are not widely used yet?

**Comment by GingkoFr** [comment]
Named arguments are a PHP 8 feature, which I do not have and will not have for some time as I rely on Debian, and even the latest Debian release still provides PHP 7.

Anyway you are the creator of SQL-Formatter, you do what you want, what is really interesting me is having the (implicitly) suggested options actually implemented, and my suggestion was just an idea for doing it more easily.

**Comment by greg0ire** [comment]
That's a better argument. Still, you are not forced to use named arguments, you could call the named constructor with all the options specified.

> Anyway you are the creator of SQL-Formatter

Actually I'm not, see https://github.com/doctrine/sql-formatter#history

There is another issue with bitmasks: it can only handle boolean, which means it would not be able to handle `indentString`, or any other non-boolean option.

IMO what would be best is either a Config object as proposed by @SenseException or named arguments.
